Generate Random number

In [9]:
import numpy as np

print(np.random.rand())
print(np.random.rand(5))

0.6095457363382017
[0.40354164 0.46571362 0.2977921  0.38666404 0.84685734]


random integer

In [7]:
print(np.random.randint(1,10))
print(np.random.randint(1,100,size=5))

6
[19 87  2 50 27]


random array (matrix)

In [10]:
print(np.random.rand(2,3))

[[0.60827389 0.26228041 0.39290325]
 [0.21644681 0.18238516 0.25729224]]


choice (random selection)

In [14]:
data=[2,3,4,5]
print(np.random.choice(data))

print(np.random.choice(data,size=3))

4
[5 2 4]


seed (same output)

In [25]:
np.random.seed(1)
print(np.random.rand(3))


[4.17022005e-01 7.20324493e-01 1.14374817e-04]


shuffle

In [28]:
arr=np.array([2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[6 5 2 4 3]
