Generate Random number

In [9]:
import numpy as np

print(np.random.rand())
print(np.random.rand(5))

0.6095457363382017
[0.40354164 0.46571362 0.2977921  0.38666404 0.84685734]


random integer

In [7]:
print(np.random.randint(1,10))
print(np.random.randint(1,100,size=5))

6
[19 87  2 50 27]


random array (matrix)

In [10]:
print(np.random.rand(2,3))

[[0.60827389 0.26228041 0.39290325]
 [0.21644681 0.18238516 0.25729224]]


choice (random selection)

In [14]:
data=[2,3,4,5]
print(np.random.choice(data))

print(np.random.choice(data,size=3))

4
[5 2 4]


seed (same output)

In [25]:
np.random.seed(1)
print(np.random.rand(3))


[4.17022005e-01 7.20324493e-01 1.14374817e-04]


shuffle

In [28]:
arr=np.array([2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[6 5 2 4 3]


practice part

In [27]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(2,3))
print(np.random.randint(5,10))
print(np.random.randint(1,10,size=5))

data=[1,2,3,4,5,6]
print(np.random.choice(data))
arr=np.array([1,2,3,4,5,6])
np.random.shuffle(data)
print(data,arr)

data=np.random.randn(5)
print(data)
print(np.std(data))
print(np.mean(data))

data=np.random.normal(loc=10,scale=2,size=5)
print(data)
print(np.std(data))
print(np.mean(data))


0.717701333201818
[0.74616285 0.65561918 0.01087372 0.09794506 0.44103738]
[[0.74072589 0.12244674 0.94952133]
 [0.05983638 0.06151472 0.69498691]]
5
[8 8 5 6 4]
4
[5, 2, 3, 4, 1, 6] [1 2 3 4 5 6]
[ 1.39351838  1.64480124 -0.76196319 -0.12572442  2.217333  ]
1.126445834545323
0.8735930015528524
[10.63441007  9.22906888  9.24966861 10.37717042 10.04069872]
0.5761480667744967
9.90620334103563
