list vs array

In [3]:
import numpy as np

lst=[1,2,3,4]
print(lst)

#1D array
arr1=np.array([1,2,3,4,5])
print(arr1)

#2D array
arr2=np.array([
    [2,3,4,5],
    [3,4,5,6]
])
print(arr2)

[1, 2, 3, 4]
[1 2 3 4 5]
[[2 3 4 5]
 [3 4 5 6]]


array properties

In [6]:
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

(2, 4)
8
2


special array

In [9]:
print(np.zeros((3,4)))
print(np.ones((2,3)))
print(np.arange(1,10))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]
