Basic operations

In [2]:
import numpy as np

arr=np.array([2,3,4,5,6,7])

print(arr+3)
print(arr/2)

[ 5  6  7  8  9 10]
[1.  1.5 2.  2.5 3.  3.5]


array versus array operation

In [8]:
a=np.array([1,2,3])
b=np.array([2,3,4])

print(a+b)
print(a*b)

[3 5 7]
[ 2  6 12]


methods

In [7]:
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())

27
7
2
4.5


standard deviation and variance

In [9]:
print(arr.std())
print(arr.var())

1.707825127659933
2.9166666666666665


square and square root

In [11]:
print(np.square(arr))
print(np.sqrt(arr))

[ 4  9 16 25 36 49]
[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]


practice part

In [12]:
#basic operation
import numpy as np
arr=np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])

print(arr+1)
print(arr*2)
print(arr/2)

#function
print(arr.sum())
print(arr.max())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(np.sqrt(arr))
print(np.square(arr))

[[2 3 4 5 6 7 8]
 [3 4 5 6 7 8 9]]
[[ 2  4  6  8 10 12 14]
 [ 4  6  8 10 12 14 16]]
[[0.5 1.  1.5 2.  2.5 3.  3.5]
 [1.  1.5 2.  2.5 3.  3.5 4. ]]
63
8
4.5
2.0615528128088303
4.25
[ 3  5  7  9 11 13 15]
[28 35]
[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131]
 [1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
  2.82842712]]
[[ 1  4  9 16 25 36 49]
 [ 4  9 16 25 36 49 64]]
