Indexing

In [7]:
import numpy as np

arr1=np.array([1,3,4,2,5,6])
print(arr1[2])

arr2=np.array([[2,3,4,5,7,8],[2,3,4,5,6,8]])
print(arr2[1][1])

#short way
print(arr2[1,2])

4
3
4


Slicing

In [12]:
print(arr1[0:3])
print(arr1[0:5:2])

print(arr2[0:2,0:2])

[1 3 4]
[1 4 5]
[[2 3]
 [2 3]]
