array filtering

In [3]:
import numpy as np
arr=np.array([10,9,8,49,20,45,1,2,43])
print(arr>2)
print(arr[arr>3])

[ True  True  True  True  True  True False False  True]
[10  9  8 49 20 45 43]


multiple condition

In [9]:
import numpy as np
arr=np.array([10,9,8,49,20,45,1,2,43])
print(arr[(arr>9) & (arr<30)])
print(arr[(arr<5) | (arr>30)])

arr[arr<10]=11
print(arr)

[10 20]
[49 45  1  2 43]
[10 11 11 49 20 45 11 11 43]
