Reshape

In [2]:
import numpy as np

arr=np.array([1,3,2,4,5,7])
print(arr.reshape(3,2))

[[1 3]
 [2 4]
 [5 7]]


automatic reshape

In [7]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1.reshape(3,-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Flatten

In [9]:
arr2=np.array([[2,3,4],[4,5,6]])
print(arr2.flatten())

[2 3 4 4 5 6]


ravel

In [10]:
print(arr2.ravel())

[2 3 4 4 5 6]


In [ ]:
Stacking

In [ ]:

a=np.array([1,2,3])
b=np.array([4,5,6])
#hstack
print(np.hstack((a,b)))
#vstack
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


split

In [13]:
c=np.array([1,2,3,4,5,6])
print(np.split(c,3))

[array([1, 2]), array([3, 4]), array([5, 6])]
