Dot product

In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


matrix multiplication

In [5]:
c=np.array([
    [1,2],
    [3,4]
])

d=np.array([
    [2,3],
    [4,5]
])
result=np.matmul(c,d)
print(result)

[[10 13]
 [22 29]]


transpose

In [7]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr.T)

[[1 5]
 [2 6]
 [3 7]]


determinant

In [9]:
print(np.linalg.det(d))

-2.0


Inverse

In [10]:
print(np.linalg.inv(d))

[[-2.5  1.5]
 [ 2.  -1. ]]
